zuul:
   #ignored-patterns: /**/member/**
   SendErrorFilter:
      error:
         disable: true
   routes:
      config-service:
         path: /config-service/**
         serviceId: configapp
      employee-service:
         path: /employee-service/**
         serviceId: employeeapp
      member-service:
         path: /member-service/**
         serviceId: memberapp
      mate-service:
         path: /mate-service/**
         serviceId: meetapp
         customSensitiveHeaders: true 
         sensitiveHeaders:            
      forward-mate-service:           
         path: /forward-mate-service/**
         url: forward:/gatewaylocal
server:
   port: 1111
   servlet:
      context-path: /petergateway

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 5000
  ConnectTimeout: 5000
hystrix: 
  command: 
    default:  
      execution: 
        timeout: 
          enabled: true 
        isolation: 
          thread: 
            timeoutInMilliseconds: 50000 

spring:
    rabbitmq:
       host: 192.168.101.7
       port: 5672
       username: peter_mq
       password: peter_mq_pwd
a:
   b: aabb