zuul:
   ignoredServices: '*'
   max:
     host:
      connections: 500
   host:
     socket-timeout-millis: 10000
     connect-timeout-millis: 10000
   #ignored-patterns: /**/member/**
   SendErrorFilter:
      error:
         disable: true
   routes:
      config-service:
         path: /config-service/**
         serviceId: configapp
      employee-service:
         path: /employee-service/**
         serviceId: employeeapp
      member-service:
         path: /member-service/**
         serviceId: memberapp
      mate-service:
         path: /mate-service/**
         serviceId: meetapp
         customSensitiveHeaders: true 
         sensitiveHeaders:            
      forward-mate-service:           
         path: /forward-mate-service/**
         url: forward:/gatewaylocal
server:
   port: 1111
   servlet:
      context-path: /petergateway
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 10000
  ConnectTimeout: 10000
hystrix: 
  command: 
    default:  
      execution: 
        timeout: 
          enabled: true 
        isolation: 
          thread: 
            timeoutInMilliseconds: 10000

spring:
    rabbitmq:
       host: 192.168.101.7
       port: 5672
       username: peter_mq
       password: peter_mq_pwd
security:
  basic:
    enabled: false
  oauth2:
    client:
      access-token-uri: http://192.168.101.7:5555/petersecurity/oauth/token
      user-authorization-uri: http://192.168.101.7:5555/petersecurity/oauth/authorize
      client-id: peter_client
      client-secret: peter_secret
    resource:
      jwt:
        key-value: peter_jwt_converter